/**
 * 心智 Schema v0（2 周验证版，6 个真实客群原型）
 * 完整十六层 Schema 见方案文档；v0 只保留验证所需的关键层：
 * 来店目的 / 价格心理 / 服务期待 / 食物要求 / 等待容忍 / 表达方式 / 投诉倾向 / 情绪恢复 / 隐性心理(子集)
 * 参数 = 专家先验（E），Phase 4 用真实数据拟合。
 */

export const PERSONA_ARCHETYPES = {
  family_dinner: {
    key: 'family_dinner',
    label: '家庭聚餐',
    intent: 'family',
    weights: { price: 0.25, taste: 0.30, service: 0.20, environment: 0.10, efficiency: 0.10, emotion: 0.05 },
    price_mind: { budget_limit: 'flexible', value_expectation: 0.7, upsell_acceptance: 'neutral' },
    service_expectation: { speed: 'high', professional: 'medium', initiative: 'high' },
    food: { portion: 0.8, stability: 0.6, health: 0.5 },
    tolerance: { wait_food: 15, queue: 10 },
    mistake_tolerance: { wrong_dish: 0.4, late_food: 0.5, attitude: 0.2 },
    expression: 'polite',
    complaint: 'face_to_face',
    emotion: { anger_threshold: 60, recovery_speed: 0.6, memory_length: 'short' },
    hidden: { face: 0.3, recognition: 0.4, novelty: 0.4, risk_aversion: 0.6, child_service: 0.8 },
  },
  couple_date: {
    key: 'couple_date',
    label: '情侣约会',
    intent: 'couple',
    weights: { price: 0.15, taste: 0.25, service: 0.20, environment: 0.25, efficiency: 0.10, emotion: 0.05 },
    price_mind: { budget_limit: 'flexible', value_expectation: 0.6, upsell_acceptance: 'neutral' },
    service_expectation: { speed: 'medium', professional: 'medium', initiative: 'medium' },
    food: { presentation: 0.8, taste: 0.6 },
    tolerance: { wait_food: 20, queue: 15 },
    mistake_tolerance: { wrong_dish: 0.3, late_food: 0.5, attitude: 0.2 },
    expression: '委婉',
    complaint: 'low',
    emotion: { anger_threshold: 55, recovery_speed: 0.7, memory_length: 'short' },
    hidden: { face: 0.5, recognition: 0.3, novelty: 0.6, risk_aversion: 0.4, atmosphere: 0.9 },
  },
  business_banquet: {
    key: 'business_banquet',
    label: '商务宴请',
    intent: 'business',
    weights: { price: 0.10, taste: 0.20, service: 0.30, environment: 0.20, efficiency: 0.15, emotion: 0.05 },
    price_mind: { budget_limit: 'flexible', value_expectation: 0.7, upsell_acceptance: 'welcome' },
    service_expectation: { speed: 'medium', professional: 'high', initiative: 'high' },
    food: { presentation: 0.7, stability: 0.7 },
    tolerance: { wait_food: 25, queue: 15 },
    mistake_tolerance: { wrong_dish: 0.05, late_food: 0.4, attitude: 0.1 },
    expression: 'direct',
    complaint: 'manager_only',
    emotion: { anger_threshold: 65, recovery_speed: 0.8, memory_length: 'long' },
    hidden: { face: 0.95, recognition: 0.5, novelty: 0.4, risk_aversion: 0.7 },
  },
  repeat_member: {
    key: 'repeat_member',
    label: '老会员',
    intent: 'repeat_visit',
    weights: { price: 0.15, taste: 0.30, service: 0.25, environment: 0.10, efficiency: 0.10, emotion: 0.10 },
    price_mind: { budget_limit: 'flexible', value_expectation: 0.8, upsell_acceptance: 'neutral' },
    service_expectation: { speed: 'medium', professional: 'high', initiative: 'high' },
    food: { stability: 0.9, taste: 0.8 },
    tolerance: { wait_food: 20, queue: 15 },
    mistake_tolerance: { wrong_dish: 0.3, late_food: 0.5, attitude: 0.2 },
    expression: '委婉',
    complaint: 'private',
    emotion: { anger_threshold: 70, recovery_speed: 0.5, memory_length: 'long' },
    hidden: { face: 0.3, recognition: 0.95, novelty: 0.3, risk_aversion: 0.5, expectation: 0.8 },
  },
  price_sensitive: {
    key: 'price_sensitive',
    label: '价格敏感',
    intent: 'work_meal',
    weights: { price: 0.45, taste: 0.25, service: 0.10, environment: 0.05, efficiency: 0.10, emotion: 0.05 },
    price_mind: { budget_limit: 'strict', value_expectation: 0.9, upsell_acceptance: 'hate', coupon_dependence: 0.8 },
    service_expectation: { speed: 'high', professional: 'low', initiative: 'low' },
    food: { portion: 0.8, taste: 0.5 },
    tolerance: { wait_food: 15, queue: 10 },
    mistake_tolerance: { wrong_dish: 0.4, late_food: 0.4, attitude: 0.3 },
    expression: 'direct',
    complaint: 'online',
    emotion: { anger_threshold: 50, recovery_speed: 0.5, memory_length: 'medium' },
    hidden: { face: 0.2, recognition: 0.2, novelty: 0.3, risk_aversion: 0.8 },
  },
  quality_focused: {
    key: 'quality_focused',
    label: '品质型',
    intent: 'taste',
    weights: { price: 0.10, taste: 0.40, service: 0.15, environment: 0.15, efficiency: 0.05, emotion: 0.15 },
    price_mind: { budget_limit: 'unlimited', value_expectation: 0.85, upsell_acceptance: 'neutral' },
    service_expectation: { speed: 'low', professional: 'medium', initiative: 'medium' },
    food: { freshness: 0.95, taste: 0.85, temperature: 0.8 },
    tolerance: { wait_food: 30, queue: 20 },
    mistake_tolerance: { wrong_dish: 0.3, late_food: 0.7, attitude: 0.3 },
    expression: 'direct',
    complaint: 'online',
    emotion: { anger_threshold: 60, recovery_speed: 0.4, memory_length: 'long' },
    hidden: { face: 0.2, recognition: 0.2, novelty: 0.8, risk_aversion: 0.2 },
  },
};

export const PERSONA_KEYS = Object.keys(PERSONA_ARCHETYPES);
