-- 剩余共享表唯一键：空库中不存在的可选表跳过；存在时补 tenant_id。
DO $$
DECLARE x JSONB; t TEXT; oldc TEXT; newc TEXT; cols TEXT; missing INT;
BEGIN
  FOR x IN SELECT value FROM jsonb_array_elements('[
    ["employees","employees_pkey","employees_pkey","username"],["users","users_username_key","users_username_key","username"],["user_sessions","user_sessions_pkey","user_sessions_pkey","username"],["user_reads","user_reads_pkey","user_reads_pkey","username,module,item_key"],["feishu_pending_replies","feishu_pending_replies_pkey","feishu_pending_replies_pkey","open_id"],["feishu_pending_pllm_decisions","feishu_pending_pllm_decisions_pkey","feishu_pending_pllm_decisions_pkey","open_id"],["agent_v2_data_alert_dedupe","agent_v2_data_alert_dedupe_pkey","agent_v2_data_alert_dedupe_pkey","dedupe_key"],["customer_identities","customer_identities_identity_type_identity_value_key","customer_identities_identity_type_identity_value_key","identity_type,identity_value"],["daily_report_attendance_register","daily_report_attendance_register_store_report_date_key","daily_report_attendance_register_store_report_date_key","store,report_date"],["daily_reports","daily_reports_store_date_key","daily_reports_store_date_key","store,date"],["generated_posters","generated_posters_poster_key_key","generated_posters_poster_key_key","poster_key"],["master_tasks","master_tasks_task_id_tenant_id_key","master_tasks_task_id_tenant_id_key","task_id"],["public_promo_tasks","public_promo_tasks_task_key_key","public_promo_tasks_task_key_key","task_key"],["sales_growth_snapshot","sales_growth_snapshot_snapshot_date_store_code_dish_name_key","sales_growth_snapshot_snapshot_date_store_code_dish_name_key","snapshot_date,store_code,dish_name"],["store_duty_bindings","store_duty_bindings_username_store_key","store_duty_bindings_username_store_key","username,store"],["store_ratings","store_ratings_store_brand_period_key","store_ratings_store_brand_period_key","store,brand,period"],["store_wecom_configs","store_wecom_configs_store_id_key","store_wecom_configs_store_id_key","store_id"],["strategy_experiments","strategy_experiments_experiment_code_key","strategy_experiments_experiment_code_key","experiment_code"],["strategy_rules","strategy_rules_scenario_root_unique","strategy_rules_scenario_root_unique","scenario,root_cause"],["table_visit_records","table_visit_records_feishu_record_id_key","table_visit_records_feishu_record_id_key","feishu_record_id"],["training_sessions","training_sessions_employee_username_topic_id_key","training_sessions_employee_username_topic_id_key","employee_username,topic_id"]
  ]'::jsonb) LOOP
    t:=x->>0; oldc:=x->>1; newc:=x->>2; cols:=x->>3;
    SELECT count(*) INTO missing FROM unnest(string_to_array(cols||',tenant_id',',')) c WHERE NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=t AND column_name=trim(c));
    IF to_regclass('public.'||t) IS NOT NULL AND missing=0 THEN
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',t,oldc);
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I UNIQUE (%s,tenant_id)',t,newc,cols);
    END IF;
  END LOOP;
END $$;
